version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: monthly
    assignees:
      - m-yosefpor
    labels:
      - dependencies

  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    assignees:
      - m-yosefpor
    labels:
      - dependencies
